import { Inter } from "next/font/google";
import "./globals.css";
import CustomNavbar from "@/components/CustomNavbar";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import UserProvider from "@/context/userProvider";
import Footer from "@/components/Footer";
import { ThemeProvider } from "next-themes";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Stock Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className }>
      <ThemeProvider>
      <UserProvider>
      <CustomNavbar/>
      <ToastContainer />
        {children}
        <hr className="border-gray-500 mt-52" />
        <Footer/>
        </UserProvider>
        </ThemeProvider>
        
        </body>
    </html>
  );
}
